# Generated by Django 5.1.4 on 2026-07-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApis', '0017_manuscript_editorialdecision_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
